### ISSUE TITLE
Directory issue within modules.php when setting up new Altis local chassis

### ISSUE THREAD

**Issue by kevinlangleyjr** [humanmade/altis-cms-installer#30] opened 2020-01-30 01:26 UTC
Following the Getting started guide within the Altis documentation, I am seeing an issue with the generated `modules.php` file.

For some reason locally the file is being saved with the following content:

```php
<?php
/**
 * Altis Module Loader.
 *
 * DO NOT EDIT THIS FILE.
 */

// Load altis/analytics.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/analytics/load.php';
// Load altis/cloud.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/cloud/load.php';
// Load altis/cms.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/cms/load.php';
// Load altis/core.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/core/load.php';
// Load altis/dev-tools.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/dev-tools/load.php';
// Load altis/documentation.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/documentation/load.php';
// Load altis/enhanced-search.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/enhanced-search/load.php';
// Load altis/local-chassis.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/local-chassis/load.php';
// Load altis/local-server.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/local-server/load.php';
// Load altis/media.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/media/load.php';
// Load altis/multilingual.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/multilingual/load.php';
// Load altis/security.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/security/load.php';
// Load altis/seo.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/seo/load.php';
// Load altis/sso.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/sso/load.php';
// Load altis/workflow.
require_once '/Users/klangley/Development/Active/altis-test-site/vendor/altis/cms-installer/inc/composer' . '/altis/workflow/load.php';
```

I am somewhat puzzled here what could be making that change on setup as I see we're using `__DIR__` there in this repo here to create the `modules.php` file.

I've verified this by setting up two sites and had the exact same issue.

**Comment by roborourke** [comment] 2020-01-30 12:06
That's concerning! do you get the same content again if you run `composer dump-autoload` afterwards?

For clarity here can you confirm it was just this step that gave you the bad `modules.php`?

- `composer create-project altis/skeleton my-project`

I was unable to reproduce this myself. If you can reproduce it consistently could you try running `composer clear-cache` and try it again?

**Comment by kevinlangleyjr** [comment] 2020-01-30 14:36
Not sure what could have resulted in this happening on two setups, but dumping the autoload fixed the issue. Then I created a new Altis project just as I had before and I didn't encounter the issue again.

**Comment by roborourke** [comment] 2020-01-30 15:26
Fun... for the record I did see this once myself but once it started working properly I couldn't get to happen again for the life of me. Pretty sure it's related to an older version of the CMS Installer package. Cheers for following up.

**Comment by kevinlangleyjr** [comment] 2020-02-03 22:36
Looks like I am able to replicate it by running `composer require owner/package` in the project root after the initial setup of the project.

It seems like that's when the autoloaders are created and the `modules.php` file gets full paths instead of using `__DIR__`.

**Comment by roborourke** [comment] 2020-02-04 09:43
It'll be regenerating the autoloaders, `modules.php` is generated on that hook. It's kinda wild that it does that, the line literally echoes out `__DIR__`:

https://github.com/humanmade/altis-cms-installer/blob/master/inc/composer/class-plugin.php#L107

Maybe there's some post processing going on in composer...

**Comment by roborourke** [comment] 2020-02-04 10:11
Confirmed! WTAF

**Comment by roborourke** [comment] 2020-02-04 10:37
Turns out this happens only in certain composer contexts, namely when plugins are registered for the first time which seems to happen during `composer require` calls.

Composer's PluginManager class reads and eval()s the plugin class files replacing constants like `__DIR__`, `__FILE__` and `__CLASS__` with the fully qualified values which is what was causing us the problem.

Thanks for figuring out the step to reproduce @kevinlangleyjr!

Closed by #31

**Closed as completed** 2020-02-04 13:30 UTC
Labels: bug

**Comment by kevinlangleyjr** [comment] 2020-02-04 14:01
Awesome to hear this has been fixed! Thanks @roborourke! 🎉

**Comment by roborourke** [comment] 2020-02-04 14:08
`composer update` should get the latest version, 0.4.1
